import { ArrowRight, Award, CheckCircle2, HeartHandshake, History, ShieldCheck, Target, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import PageHeader from '@/components/PageHeader';
import { shopInfo, stats } from '@/lib/catalog';

export default function About() {
  return (
    <main>
      <PageHeader eyebrow="Our story" title="Powering progress since 1985." subtitle="A family-run electrical business built on good advice, genuine products and service that lasts." crumbs={[{ label: 'Home', to: '/' }, { label: 'About Us' }]} />
      <section className="container-page grid items-center gap-12 py-20 md:grid-cols-2 md:py-28"><div><p className="section-eyebrow"><span className="h-px w-8 bg-brand-500" /> Four decades of trust</p><h2 className="section-title mt-3">From one shop to a complete power partner.</h2><div className="mt-5 space-y-4 text-base leading-relaxed text-ink-600"><p>Since 1985, Avinash Electricals has served Old Panvel and the wider Navi Mumbai region with one guiding principle: recommend the right product, not the most expensive one. From individual homes to entire housing societies, and from small shops to busy clinics, offices, hospitals, schools, and function halls, we bring the same honest, personalised approach to every customer we serve.</p><p>Our expertise spans everyday electrical essentials such as home inverters and wiring solutions, right through to the professional design and installation of complete rooftop solar power systems. Combining four decades of old-school trust with modern power technology, our team ensures every installation is safe, efficient, and built to last — because for us, doing right by the customer has never gone out of style.</p></div><Link to="/contact" className="btn-primary mt-8">Work with us <ArrowRight className="h-4 w-4" /></Link></div><div className="relative"><div className="h-[420px] w-full overflow-hidden rounded-2xl shadow-card"><img src="/images/about-shop.jpg" alt="Warmly lit electrical shop display" className="h-full w-full object-cover" /></div><div className="absolute -bottom-5 -left-5 rounded-2xl bg-gold-500 p-5 text-ink-950 shadow-card"><p className="font-display text-4xl font-extrabold">1985</p><p className="text-xs font-bold uppercase tracking-wider">Established</p></div></div></section>
      <section className="bg-white"><div className="container-page grid gap-6 py-20 sm:grid-cols-2 lg:grid-cols-4">{stats.map((s) => <div key={s.label} className="rounded-2xl border border-ink-100 p-6 text-center"><p className="font-display text-4xl font-extrabold text-brand-700">{s.value}</p><p className="mt-2 text-xs font-bold uppercase tracking-wider text-ink-500">{s.label}</p></div>)}</div></section>
      <section className="container-page py-20 md:py-28"><div className="text-center"><p className="section-eyebrow justify-center"><span className="h-px w-8 bg-brand-500" /> What guides us</p><h2 className="section-title mt-3">Values you can feel in every job.</h2></div><div className="mt-12 grid gap-6 md:grid-cols-3">{[{ icon:HeartHandshake,title:'Honest advice',desc:'We ask about your actual needs, explain the options clearly and never oversell.'},{icon:ShieldCheck,title:'Quality first',desc:'Genuine brands, safe installation and workmanship we are proud to put our name on.'},{icon:Target,title:'Built to last',desc:'We think beyond the sale — with reliable support, service and practical maintenance.'}].map(({icon:Icon,title,desc})=><div key={title} className="card p-7"><div className="grid h-12 w-12 place-items-center rounded-xl bg-brand-50 text-brand-600"><Icon className="h-6 w-6" /></div><h3 className="mt-5 font-display text-2xl font-bold text-ink-900">{title}</h3><p className="mt-2 text-sm leading-relaxed text-ink-500">{desc}</p></div>)}</div></section>
      <section className="bg-ink-900 text-white"><div className="container-page grid gap-12 py-20 md:grid-cols-2 md:items-center"><div><p className="section-eyebrow text-gold-400"><span className="h-px w-8 bg-gold-400" /> How we work</p><h2 className="mt-3 font-display text-4xl font-extrabold">The right solution starts with the right questions.</h2><p className="mt-5 leading-relaxed text-ink-300">Whether you need a home inverter or a complete commercial setup, we begin with a site visit and load check. Then we recommend a clear, practical solution — with a transparent quote and no surprises.</p></div><div className="space-y-4">{['Understand your power needs','Recommend the right products','Install safely and neatly','Stay available after the sale'].map((step,i)=><div key={step} className="flex items-center gap-4 rounded-xl border border-white/10 bg-white/5 p-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-gold-500 font-display text-lg font-bold text-ink-950">{i+1}</span><span className="font-semibold">{step}</span><CheckCircle2 className="ml-auto h-5 w-5 text-brand-400" /></div>)}</div></div></section>
      <section className="container-page py-20 text-center"><Award className="mx-auto h-10 w-10 text-gold-500" /><h2 className="section-title mt-4">Let's power your next project.</h2><p className="mx-auto mt-4 max-w-xl text-ink-500">Visit our store in Old Panvel or call us for a free consultation.</p><Link to="/contact" className="btn-primary mt-7">Contact Avinash Electricals <ArrowRight className="h-4 w-4" /></Link></section>
    </main>
  );
}
