import { ArrowRight, BatteryCharging, CheckCircle2, Clock3, ShieldCheck, Sun, Truck, Wrench, Zap } from 'lucide-react';
import { Link } from 'react-router-dom';
import PageHeader from '@/components/PageHeader';
import { services, shopInfo } from '@/lib/catalog';

const icons = { Zap, Sun, Wrench, ShieldCheck, BatteryCharging, Truck };

export default function Services() {
  return (
    <main>
      <PageHeader eyebrow="Support that stays" title="More than products. Complete power care." subtitle="From the first site survey to annual maintenance, our electricians help your system perform at its best." crumbs={[{ label: 'Home', to: '/' }, { label: 'Services' }]} />
      <section className="container-page py-20 md:py-28"><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{services.map((service) => { const Icon = icons[service.icon as keyof typeof icons]; return <div key={service.title} className="card group p-7 transition duration-300 hover:-translate-y-1 hover:border-brand-200"><div className="flex items-start justify-between"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-brand-50 text-brand-600 transition group-hover:bg-brand-600 group-hover:text-white"><Icon className="h-7 w-7" /></div><span className="font-display text-3xl font-bold text-ink-100">0{services.indexOf(service)+1}</span></div><h2 className="mt-7 font-display text-2xl font-bold text-ink-900">{service.title}</h2><p className="mt-3 text-sm leading-relaxed text-ink-500">{service.desc}</p><Link to="/contact" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-brand-600">Book this service <ArrowRight className="h-4 w-4" /></Link></div> })}</div></section>
      <section className="bg-white"><div className="container-page grid items-center gap-12 py-20 md:grid-cols-2 md:py-28"><div><p className="section-eyebrow"><span className="h-px w-8 bg-brand-500" /> Our process</p><h2 className="section-title mt-3">Professional from first call to final check.</h2><p className="mt-5 text-base leading-relaxed text-ink-600">Every job is planned, explained and finished properly. We keep you informed, protect your space and test everything before we leave.</p><div className="mt-8 space-y-5">{['Tell us what you need', 'Get a clear quote and timeline', 'We install with care', 'Enjoy dependable support'].map((step, i) => <div key={step} className="flex gap-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-brand-600 font-display text-lg font-bold text-white">{i+1}</span><div><h3 className="font-bold text-ink-800">{step}</h3><p className="mt-1 text-sm text-ink-500">{['Call, WhatsApp or visit our store for a quick conversation.', 'No hidden charges — just the work and products you need.', 'Our trained electricians keep the site safe and tidy.', 'We stay available for maintenance, repairs and advice.'][i]}</p></div></div>)}</div></div><div className="relative"><div className="h-[470px] w-full overflow-hidden rounded-2xl shadow-card"><img src="/images/services-switchboard.jpg" alt="Electrician working on a switchboard" className="h-full w-full object-cover" /></div><div className="absolute bottom-5 left-5 right-5 rounded-xl bg-ink-950/90 p-5 text-white backdrop-blur"><div className="flex items-center gap-3"><Clock3 className="h-6 w-6 text-gold-400" /><div><p className="font-bold">Trusted Power Experts</p><p className="mt-0.5 text-xs text-ink-300">Inverters, batteries, UPS & solar — all under one roof.</p></div></div></div></div></div></section>
      <section className="container-page py-20"><div className="rounded-3xl bg-brand-600 p-8 text-white md:p-12"><div className="grid items-center gap-10 md:grid-cols-[1fr_auto]"><div><p className="section-eyebrow text-brand-100"><span className="h-px w-8 bg-brand-100" /> Ready when you are</p><h2 className="mt-3 font-display text-4xl font-extrabold">Let's get your power sorted.</h2><p className="mt-4 max-w-xl text-brand-100">Book a free consultation or call us for same-day service across Navi Mumbai.</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{['Free load consultation', 'Genuine warranty products', 'Licensed technicians', 'After-sales support'].map((x)=><div key={x} className="flex items-center gap-2 text-sm font-semibold"><CheckCircle2 className="h-4 w-4 text-gold-300" /> {x}</div>)}</div></div><div className="flex flex-col gap-3"><Link to="/contact" className="btn-gold">Book a consultation <ArrowRight className="h-4 w-4" /></Link><a href={`tel:${shopInfo.phone.replace(/\s/g,'')}`} className="inline-flex items-center justify-center gap-2 rounded-full border border-white/30 px-6 py-3 text-sm font-semibold text-white transition hover:bg-white/10">Call {shopInfo.phone}</a></div></div></div></section>
    </main>
  );
}
